version: '3.1'

services:

  db:
    image: drycc/postgres:v1.0.0
    restart: always
    environment:
      PGCTLTIMEOUT: 1200
      BACKUP_FREQUENCY: 1s
      DATABASE_STORAGE: minio
      DRYCC_MINIO_SERVICE_HOST: 10.233.40.14
      DRYCC_MINIO_SERVICE_PORT: 9000
    ports:
      - 5432:5432
    volumes:
      - ./volumes/data:/var/lib/postgresql/data
      - ./volumes/database:/var/run/secrets/drycc/database/creds
      - ./volumes/objectstore:/var/run/secrets/drycc/objectstore/creds
